# This is a placeholder hardware configuration for Dell Latitude 7280
# You MUST replace this with the actual hardware configuration generated by:
# sudo nixos-generate-config --show-hardware-config > /etc/nixos/hardware-configuration.nix
# Then copy the contents here.

{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # PLACEHOLDER - Replace with actual hardware configuration
  # This is just a template to prevent build errors
  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  # Filesystem configuration handled by disko - do not define fileSystems here
  # swapDevices handled by disko swapfile

  # Enables DHCP on each ethernet and wireless interface.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
