#!/bin/bash
# Shell color configuration generated by matugen
# This file contains Material You colors for shell applications

# Material You color variables
export PRIMARY="{{colors.primary.hex}}"
export ON_PRIMARY="{{colors.on_primary.hex}}"
export SECONDARY="{{colors.secondary.hex}}"
export ON_SECONDARY="{{colors.on_secondary.hex}}"
export TERTIARY="{{colors.tertiary.hex}}"
export ON_TERTIARY="{{colors.on_tertiary.hex}}"
export SURFACE="{{colors.surface.hex}}"
export ON_SURFACE="{{colors.on_surface.hex}}"
export BACKGROUND="{{colors.background.hex}}"
export ON_BACKGROUND="{{colors.on_background.hex}}"
export ERROR="{{colors.error.hex}}"
export ON_ERROR="{{colors.on_error.hex}}"

# Custom Claude colors
export CLAUDE_ORANGE="{{colors.custom.claude_orange.hex}}"
export CLAUDE_SECONDARY="{{colors.custom.claude_secondary.hex}}"
export CLAUDE_TERTIARY="{{colors.custom.claude_tertiary.hex}}"
export CLAUDE_BACKGROUND="{{colors.custom.claude_background.hex}}"
export CLAUDE_SURFACE="{{colors.custom.claude_surface.hex}}"

# Export for use in other scripts
export MATUGEN_PRIMARY="$PRIMARY"
export MATUGEN_SECONDARY="$SECONDARY"
export MATUGEN_BACKGROUND="$BACKGROUND"
export MATUGEN_SURFACE="$SURFACE"