keys:
  - &admin_tom age1vvqsmuze45cqpuzlm4cyzh05g6wy58uq35lzak4stqc3lgrlxseq4e3rfr

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *admin_tom
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *admin_tom