# SOPS configuration file
# This file defines encryption rules and key access

keys:
  # System host key (will be populated after first boot)
  - &host_gti age1k6egepq8r25nxjcew7wl862hmlm3pa28fwvle8eyy0xk79jqaadskuz2k6
  
  # User age key (generate with: age-keygen -o ~/.config/sops/age/keys.txt)
  - &user_tom age1xrkzc96sczpmt0sx5yjjevpkgd9xyf98xyyyct6x5sazhn2tfyuqlzeg4l
  
  # YubiKey age plugin (uncomment after YubiKey setup)
  # - &yubikey_tom age1yubikey1...

creation_rules:
  # System-wide secrets
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *host_gti
          - *user_tom
          # - *yubikey_tom  # Uncomment after YubiKey setup
  
  # User-specific secrets
  - path_regex: user-secrets\.yaml$
    key_groups:
      - age:
          - *user_tom
          # - *yubikey_tom  # Uncomment after YubiKey setup

# Example encrypted file creation:
# 1. Generate keys:
#    sudo ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub  # System key
#    age-keygen -o ~/.config/sops/age/keys.txt            # User key
#    age-plugin-yubikey --identity > ~/.config/sops/age/yubikey.txt  # YubiKey
# 
# 2. Update this file with actual public keys
# 
# 3. Create encrypted files:
#    sops secrets/secrets.yaml
#    sops secrets/user-secrets.yaml